[http]
addr = ":8888"
allowed_origins = []

[kafka]
brokers = ["kafka:9092"]
group_id = "notifier"
topic = "saga.orchestrator.state.changed"

[ws]
ping_interval_sec = 20
write_timeout_sec = 10
max_message_bytes = 1048576

[security]
require_auth = false
